### ISSUE TITLE
스시코우지

### ISSUE THREAD

**Issue by SangminOut** [SangminOut/SangminOut#2]
https://store.naver.com/restaurants/detail?entry=plt&id=34550318&query=%EC%8A%A4%EC%8B%9C%EC%BD%94%EC%9A%B0%EC%A7%80

**Comment by SangminOut** [comment]
11월 14일 예약

**Comment by khg0712** [comment]
🍣

**Comment by SangminOut** [comment]
11월 18일 7시로 연기

**Comment by SangminOut** [comment]
역시 돈은 거짓말 안한다
맛있었다~
